### ISSUE TITLE
Conversion not working - returns "Voice is required."

### ISSUE THREAD

**Issue by dmazar-edipresse** [playht/text-to-speech-api#3]
I am trying to invoke the API with CURL:

`curl -H "X-User-ID:my_API_user" -H "Authorization:my_API_secret" -X POST https://play.ht/api/v1/convert -d '{"voice":"Emilia","content":"Something","title":"Something"}'`

System responds with this information:
`{"error":"Voice is required."}`

Could you provide some working examples?

**Comment by dmazar-edipresse** [comment]
OK, I've got that. API requires to have an Content Type header. So the correct example of invocation is:

`curl -H "X-User-ID:my_API_user" -H "Authorization:my_API_secret" -H "Content-Type: application/json" -X POST https://play.ht/api/v1/convert -d '{"voice":"Emilia","content":"Something","title":"Something"}'`

I think you should reflect that in the documentation

**Comment by HazemAM** [comment]
Hello @dmazar-edipresse. Thanks a lot for your feedback!
We just released [v1.0.2](https://github.com/playht/text-to-speech-api/releases/tag/v1.0.2) which addresses this issue.
